### ISSUE TITLE
analyse recorded orderbooks for market-making profitability (~5h)

### ISSUE THREAD

**Issue by shadiakiki1986** [SSOC18/crypto-recorder#1]
general
- so we've been recording hourly data on kraken orderbook for maybe 2 months now
- let's analyse the profitability of a market-maker operating on kraken BTCUSD

Steps
- create new jupyter notebook that fetches the orderbooks recorded in the database so far
- filter each hour's orderbook for the top 10 BTC
- accumulate positions of the market-maker given the strategy below

strategy
- assume initially that the best bid and best ask for 10 BTC belong to our hypothetical market-maker
- continuously aggregate bids and asks from the executed trades until one side reaches 10 BTC
- note that the above aggregation means that an aggregated bid followed by an aggregated ask will cancel each other's positions
- identify when the 10 BTC limit is reached
- if 10 BTC limit is reached for accumulated asks, stop accumulating asks from the executed trades and only accumulate trades from bids
- vice versa for bids 
- wait till the asks/bids falls down from the 10 BTC limit down to 0
- start accumulating asks/bids again

**Comment by MickMek** [comment]
Market maker simulator is up on the server, can't commit it as it seems I don't have permission to access this repository. 

For now the market maker strategy is the same as stated above, but with some modifications to avoid errors:

If the bid (or ask) inventory is lower than 10BTCs at the beginning of the hour, it will accumulate appropriate asks (or bids) normally for the end of the hour. The market maker will start accumulating one side only when a side has inventory superior to 10 BTCs in the beginning of the hour. 

This means hours with high bids (or asks) executed trades will cause the market maker to accumulates more than 10 BTCs (reaching up to 25). This also means the market maker will wait for the 10 BTC limit to fall down to 0 only in the coming hour. If the inventory is lower than 10 in the next hour, it will go back to accumulate both sides (even if it hasn't reach 0 in the last hour).
Filled positions have amount equal to 0.

**Comment by shadiakiki1986** [comment]
- permission issue fixed. Please try again now
- can you post some logs showing the operation of your strategy?

**Comment by shadiakiki1986** [comment]
- about the logs of the strategy, no need to post here because I found them in the [notebook](https://github.com/SSOC18/crypto-recorder/blob/master/notebooks/3.0-mick-lob_analysis.ipynb), but the code has no comments. It would be useful to add some comments to explain what you're doing
